AWSTemplateFormatVersion: "2010-09-09"
Description: A simple EC2 instance launched in a VPC with cloudformation
Resources:  
  Homework2ec2instance:    
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-0b0dcb5067f052a63" 
      InstanceType: "t2.micro" 
      KeyName: "new-2022"
      AvailabilityZone: "us-east-1a"
      SubnetId: "subnet-0bcc616532a87fa4f"
      Tags: 
        - Key: "Name"
          Value: "Fokoue-ec2-instance"
