AWSTemplateFormatVersion: "2010-09-09"
Description: A simple EC2 instance launched in a VPC with cloudformation

Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: [t2.nano, t2.micro, t2.small, t2.medium, t2.large, t2.xlarge, t2.2xlarge,
      t3.nano, t3.micro, t3.small, t3.medium, t3.large, t3.xlarge, t3.2xlarge,
      m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
      m5.large, m5.xlarge, m5.2xlarge, m5.4xlarge,
      c5.large, c5.xlarge, c5.2xlarge, c5.4xlarge, c5.9xlarge,
      g3.8xlarge,
      r5.large, r5.xlarge, r5.2xlarge, r5.4xlarge, r3.12xlarge,
      i3.xlarge, i3.2xlarge, i3.4xlarge, i3.8xlarge,
      d2.xlarge, d2.2xlarge, d2.4xlarge, d2.8xlarge]
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
  LatestAmiId:
    Type:  'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:  
  Myec2instance:    
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName  # References the KeyName parameter
      SecurityGroupIds: # here we are going to import the security group from the SampleNetwork tamplate and sg is a list     
        - !ImportValue 
            SampleNetworkCrossStack-SecurityGroupID
      SubnetId: # same thing here we import our subnetId 
          !ImportValue 'SampleNetworkCrossStack-SubnetID'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html><body><h1>My First WebPage by Fokoue Thomas ${AWS::Region}</h1></body></html>" > /var/www/html/index.html
      Tags: 
        - Key: Name
          Value: ec2-instance-CrossStack
  
  MyEIP: # we need to allocate and ELastic Ip address
    Type: AWS::EC2::EIP 
    Properties:
      InstanceId: !Ref Myec2instance

Outputs:
  InstanceId: 
    Description: InstanceId of the newly created EC2 instance
    Value: !GetAtt Myec2instance.PublicIp 

  PrivateDnsName:
    Description: Display the DNS name of the EC2 instance
    Value: !GetAtt Myec2instance.PrivateDnsName
    Export:
     Name: !Sub '${AWS::StackName}-Myec2instance1'

  PublicDnsName:
    Description: Display the public DNS Name of the ec2 intance
    Value: !GetAtt Myec2instance.PublicDnsName
    Export:
     Name: !Sub '${AWS::StackName}-Myec2instance2'