AWSTemplateFormatVersion: "2010-09-09"
Description: Part 1 - Build a webapp stack with CloudFormation

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0e731c8a588258d0d"
      InstanceType: "t2.micro"
      IamInstanceProfile: may2022-ssm-role
      KeyName: "jan2023-keypair"
      SubnetId: "subnet-000fbc43f773a1d24"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html><body><h1>My First WebPage by Fokoue Thomas <h1></body></html>" > /var/www/html/index.html
      Tags: 
        - Key: "Name"
          Value: "Durant"

  MyEIP: # we need to allocate and ELastic Ip address using resource
    Type: AWS::EC2::EIP 
    Properties:
      InstanceId: !Ref WebAppInstance